name: untitled
version: '${project.version}'
main: mo.first.untitled.Untitled
api-version: '1.20'
commands:
  test:
    description: test
  ClearReinforcements:
    description: Removes all reinforcements
  rm:
    description: Toggles reinforcement mode
  bunker:
    description: Command for managing bunkers
    aliases: [ bunk ]
    usage: |
      /<command> create <group_name> - Creates a new bunker group with specified name.
      /<command> add <player_name> <group_name> - Adds a player to a bunker group.
      /<command> remove <player_name> <group_name> - Removes a player from a bunker group.
      /<command> giveOwnership <player_name> <group_name> - Gives ownership of a bunker group to a player.
      /<command> display <group_name> - Displays all members of a bunker group.